{% set name = "sklearndf" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 368a42bb10c943b4626e1950c1b603164ffe108ed9ce3df93699f5e417514cb8

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py<36]

requirements:
  host:
    - pip>=20.*
  run:
    - python

test:
  imports:
    - sklearndf
    - sklearndf.classification
    - sklearndf.classification.extra
    - sklearndf.pipeline
    - sklearndf.regression
    - sklearndf.regression.extra
    - sklearndf.transformation
    - sklearndf.transformation.extra

  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/BCG-Gamma/sklearndf
  license: Apache Software License v2.0
  license_file: LICENSE
  description: |
    sklearndf is an open source library designed to address a common need with
    scikit-learn: the outputs of transformers are numpy arrays, even when the input
    is a data frame. However, to inspect a model it is essential to keep track of
    the feature names.
  dev_url: https://github.com/BCG-Gamma/sklearndf
  doc_url: https://bcg-gamma.github.io/sklearndf/
  doc_source_url: https://github.com/BCG-Gamma/sklearndf/blob/develop/README.rst

extra:
  recipe-maintainers:
    - joerg-schneider
    - j-ittner
