{% set name = "sklearndf" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 368a42bb10c943b4626e1950c1b603164ffe108ed9ce3df93699f5e417514cb8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip >=20.*
    - python >=3.6,<3.9
    - flit
    - packaging >=20
    - pandas >=0.24,<1.3
    - gamma-pytools >=1.1,<2
    - scikit-learn >=0.21,<0.24
  run:
    - boruta_py >=0.3
    - gamma-pytools >=1.1,<2
    - lightgbm >=3.0
    - numpy >=1.16,<1.21
    - packaging >=20
    - pandas >=0.24,<1.3
    - python >=3.6,<4
    - scikit-learn >=0.21,<0.24
    - scipy >=1.2,<1.6

test:
  imports:
    - sklearndf
    - sklearndf.classification
    - sklearndf.classification.extra
    - sklearndf.pipeline
    - sklearndf.regression
    - sklearndf.regression.extra
    - sklearndf.transformation
    - sklearndf.transformation.extra

  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/BCG-Gamma/sklearndf
  license: Apache Software License v2.0
  license_file: LICENSE
  description: |
    sklearndf is an open source library designed to address a common need with
    scikit-learn: the outputs of transformers are numpy arrays, even when the input
    is a data frame. However, to inspect a model it is essential to keep track of
    the feature names.
  dev_url: https://github.com/BCG-Gamma/sklearndf
  doc_url: https://bcg-gamma.github.io/sklearndf/
  doc_source_url: https://github.com/BCG-Gamma/sklearndf/blob/develop/README.rst

extra:
  recipe-maintainers:
    - joerg-schneider
    - j-ittner
