{% set name = "gamma-facet" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8e898d5bc2abc8264a559170df01d4e4a86b1677cd6c2cd7ec53bbdb634eacfe

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: True  # [py<36]

requirements:
  host:
    - pip>=20.*
    - python>=3.6,<3.9
    - flit
  run:
    - gamma-pytools>=1.1,<2
    - matplotlib>=3.0,<3.4
    - numpy>=1.16,<1.21
    - packaging>=20
    - pandas>=0.24,<1.3
    - python>=3.6,<3.9
    - scipy>=1.2,<1.6
    - shap>=0.34,<0.40
    - sklearndf>=1.1,<2

test:
  imports:
    - facet
    - facet.crossfit
    - facet.inspection
    - facet.selection
    - facet.validation
    - facet.simulation

  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/BCG-Gamma/facet
  license: Apache Software License v2.0
  license_file: LICENSE
  description: |
    FACET is an open source library for human-explainable AI. It combines sophisticated
    model inspection and model-based simulation to enable better explanations of
    your supervised machine learning models.
  dev_url: https://github.com/BCG-Gamma/facet
  doc_url: https://bcg-gamma.github.io/facet/
  doc_source_url: https://github.com/BCG-Gamma/facet/blob/develop/README.rst

extra:
  recipe-maintainers:
    - joerg-schneider
    - j-ittner
