{% set name = "gamma-pytools" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 187abc9784e60719e92802224b3b1d8a2fc22cc6d78af4d906b24f9ab12e5390

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py<36]

requirements:
  host:
    - pip>=20.*
  run:
    - python

test:
  imports:
    - pytools
    - pytools.api
    - pytools.data
    - pytools.expression
    - pytools.fit
    - pytools.parallelization
    - pytools.sphinx
    - pytools.viz

  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/BCG-Gamma/pytools
  license: Apache Software License v2.0
  license_file: LICENSE
  description: |
    A collection of generic Python extensions and tools, used across GAMMA's open-source
    libraries.
  dev_url: https://github.com/BCG-Gamma/pytools
  doc_url: https://bcg-gamma.github.io/pytools/
  doc_source_url: https://github.com/BCG-Gamma/pytools/blob/develop/README.rst

extra:
  recipe-maintainers:
    - joerg-schneider
    - j-ittner
